# Terminal settings (Ghostty)
set -g default-terminal "xterm-ghostty"
set -sa terminal-overrides ",xterm-ghostty:Tc"
set -s extended-keys on
set -as terminal-features 'xterm-ghostty:extkeys'

# Enable mouse support
set -g mouse on

# Session behavior
set -g detach-on-destroy on
set -g set-clipboard on
set -g history-limit 50000
set -s escape-time 10
set -g focus-events on
set -g automatic-rename on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# kill pane
bind-key x kill-pane

# Splits inherit current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Pane resizing
bind -n M-h resize-pane -L
bind -n M-l resize-pane -R
bind -n M-k resize-pane -U
bind -n M-j resize-pane -D

# Move window to the left
bind -n M-i swap-window -t -1\; select-window -t -1

# Move window to the right
bind -n M-o swap-window -t +1\; select-window -t +1

# Set vi mode
set-window-option -g mode-keys vi

# Use visual selection mode as vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Catppuccin theme
set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}"
